### ISSUE TITLE
`ModuleNotFoundError: No module named 'ament_package'`

### ISSUE THREAD

**Issue by goekce** [m2-farzan/ros2-foxy-PKGBUILD#10]
During build process I get the following error:

```
ModuleNotFoundError: No module named 'ament_package'
CMake Error at ament_cmake_package_templates-extras.cmake:41 (message):
  execute_process(/usr/bin/python3
  /home/u/.cache/pikaur/build/ros2-foxy/src/ros2/src/ament/ament_cmake/ament_cmake_core/cmake/package_templates/templates_2_cmake.py
  /home/u/.cache/pikaur/build/ros2-foxy/src/build/ament_cmake_core/ament_cmake_package_templates/templates.cmake)
  returned error code 1
Call Stack (most recent call first):
  CMakeLists.txt:19 (include)
```

Is `ament_package` maybe missing?

**Comment by goekce** [comment]
I did not post the first error:
```
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.defaults': (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))
```
Maybe the error is related to the not updated `colcon-core` package.

**Comment by m2-farzan** [comment]
Please see https://github.com/m2-farzan/ros2-galactic-PKGBUILD/issues/14

P.S. I strongly recommend galactic over foxy. The nature of Arch makes it difficult to maintain older versions. Even galactic package has 3 open issues, and currently requires minor manual interventions (read the issues for more info).

**Comment by goekce** [comment]
Thanks for these convenient packages dear Farzan!

**Comment by m2-farzan** [comment]
You're welcome!
